package com.github.xeounxzxu.kotestextensionsspringrestdocsexample

import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class KotestExtensionsSpringRestdocsExampleApplicationTests
